spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/capstoneLMS?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config need to be kept secret and not shared publicly, consider using environment variables or a secure vault for production
# Use environment variable in production like this => jwt.secret=${JWT_SECRET:your_default_dev_key_here}
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

#to suppress the open-in-view warning:
spring.jpa.open-in-view=false
